import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen items-center justify-center bg-green-900">
        <div className="ll m-[20%] w-full bg-red-200">
          <div className="p-2">
            <span className="">
              <h2 className="text-3xl text-gray-600">Tervs game</h2>
              <p className="text-sm text-gray-500">
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quos
                asperiores expedita deleniti eum natus voluptatum! Illo,
                architecto ab. Magnam dolor ab incidunt, delectus illo dolorem
                aut beatae aliquam alias modi.
              </p>

              <Link href="/game">
                <button>Go game</button>
              </Link>
            </span>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
