/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-north-1",
    "aws_cloud_logic_custom": [
        {
            "name": "listingAPI",
            "endpoint": "https://55an7xfuk0.execute-api.eu-north-1.amazonaws.com/staging",
            "region": "eu-north-1"
        }
    ]
};


export default awsmobile;
